name: electronic_menu
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.13.0

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_svg: ^2.3.0
  get_it: ^9.2.1
  dartz: ^0.10.1
  connectivity_plus: ^7.3.1
  dio: ^5.11.0
  hive_flutter: ^1.1.0
  flutter_bloc: ^9.1.1
  intl: ^0.20.3
  google_maps_flutter: ^2.18.0
  geolocator: ^14.0.3
  geocoding: ^5.0.0
  dotted_border: ^3.1.0
  lottie: ^3.5.1
  cached_network_image: ^4.0.0
  flutter_secure_storage: ^11.2.0
  flutter_dotenv: ^6.0.1
  shared_preferences: ^2.5.5
  flutter_native_splash: ^2.4.8
  uuid: ^4.6.0
  smooth_page_indicator: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0


flutter:

  generate: true
  uses-material-design: true

  assets:
    - .env
    - assets/images/

  fonts:
    - family: AppIcons
      fonts:
        - asset: assets/fonts/AppIcons.ttf
    - family: Coopbl
      fonts:
        - asset: assets/fonts/Coopbl.ttf